vscode:
  extensions:
    - vscjava.vscode-maven@0.18.2:qKvEoCRIWFAhA7ftT2EeUw==
    - vscjava.vscode-java-debug@0.21.0:2xtBRE0lp5AV4/J7Ptda+g==
    - redhat.java@0.48.0:EYoPv4qnT0DNzzvQHYmZow==
    - pflannery.vscode-versionlens@0.24.0:FzMGwBqMxkIHqADhVK2e2Q==